# Generated by Django 5.2.17 on 2026-09-01 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر بالجنيه')),
                ('sessions_count', models.IntegerField(default=8, verbose_name='عدد الجلسات')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشيخ / المعلم')),
                ('title', models.CharField(default='مقرئ معتمد بالقراءات', max_length=150, verbose_name='المسمى العلمي')),
                ('specialty', models.CharField(max_length=200, verbose_name='التخصص القرآني')),
                ('ijazah', models.TextField(verbose_name='الإجازات والأسانيد')),
                ('gender', models.CharField(choices=[('male', 'معلم (رجل)'), ('female', 'معلمة (امرأة)')], default='male', max_length=10, verbose_name='الجنس')),
                ('status', models.CharField(choices=[('online', 'متاح الآن 🟢'), ('busy', 'في جلسة 🔴'), ('offline', 'غير متاح ⚪')], default='online', max_length=10, verbose_name='الحالة الحالية')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='التقييم')),
                ('students_count', models.IntegerField(default=0, verbose_name='عدد الطلاب')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teachers_avatars/', verbose_name='الصورة الشخصية')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المتقدم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال / الواتساب')),
                ('gender', models.CharField(default='male', max_length=10, verbose_name='الجنس')),
                ('experience_years', models.IntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('ijazah_details', models.TextField(verbose_name='تفاصيل الإجازة والسند')),
                ('recitation_link', models.URLField(blank=True, verbose_name='رابط عينة التلاوة')),
                ('cert_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='وثيقة الإجازة/الشهادة')),
                ('status', models.CharField(choices=[('pending', 'قيد الدراسة والمراجعة'), ('approved', 'مقبول ومفعل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, max_length=100, verbose_name='معرف التليجرام')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('subscription_status', models.CharField(choices=[('unsubscribed', 'غير مشترك'), ('pending', 'قيد تأكيد فودافون كاش'), ('active', 'اشتراك نشط')], default='unsubscribed', max_length=20, verbose_name='حالة الاشتراك')),
                ('sessions_left', models.IntegerField(default=0, verbose_name='الجلسات المتبقية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
                ('active_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan', verbose_name='الباقة الحالية')),
            ],
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('is_recorded', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='VodafonePaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=20, verbose_name='رقم محفظة التحويل')),
                ('transaction_ref', models.CharField(max_length=100, verbose_name='رقم مرجع العملية')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='صورة الوصل')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تم الاعتماد والموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subscriptionplan', verbose_name='الباقة المطلوبة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='api.studentprofile')),
            ],
        ),
    ]
